/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package product.service;

import demo.sa.product.ProductServiceApplication;
import org.junit.Test;

public class ProductServiceApplicationTest {
    @Test public void testAppHasAGreeting() {
        ProductServiceApplication classUnderTest = new ProductServiceApplication();
    }
}
