/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.sa.price;

import org.junit.Test;

public class PriceServiceAppTest {
    @Test public void testAppHasAGreeting() {
        PriceServiceApp classUnderTest = new PriceServiceApp();
    }
}
