/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.sa.price;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PriceServiceApp {

    public static void main(String[] args) {
        SpringApplication.run(PriceServiceApp.class, args);
    }
}
